INSERT INTO public.units (
  name,
  type,
  status,
  address,
  city,
  province,
  state,
  country,
  zip_code,
  email,
  phone,
  website,
  latitude,
  longitude,
  description
)
VALUES
  (
    'Hospital Sao Camilo Sao Paulo',
    'Hospital',
    'Ativo',
    'Rua Martiniano de Carvalho, 851',
    'Sao Paulo',
    'Província Brasileira',
    'SP',
    'Brasil',
    '01321-001',
    'hospital.sp@saocamilo.org',
    '+551132110100',
    'https://hospitalsp.saocamilo.org',
    -23.5707,
    -46.6418,
    'Hospital de referencia da Província Brasileira.'
  ),
  (
    'Paroquia Sao Camilo Salvador',
    'Paróquia',
    'Ativo',
    'Rua da Graca, 120',
    'Salvador',
    'Província Brasileira',
    'BA',
    'Brasil',
    '40150-055',
    'paroquia.salvador@saocamilo.org',
    '+557132220200',
    'https://paroquiasalvador.saocamilo.org',
    -12.9899,
    -38.5178,
    'Paroquia com atendimento pastoral e acoes sociais.'
  ),
  (
    'Casa de Riposo San Camillo Verona',
    'Casa de Repouso',
    'Ativo',
    'Via San Marco 48',
    'Verona',
    'Província da Italia',
    'Veneto',
    'Italia',
    '37138',
    'verona@casasan.cam',
    '+390458001001',
    'https://verona.sancamillo.it',
    45.4384,
    10.9916,
    'Casa de repouso dedicada ao cuidado integral de idosos.'
  ),
  (
    'Centro Universitario San Camillo Padova',
    'Centro Universitário',
    'Ativo',
    'Via Giotto 22',
    'Padova',
    'Província da Italia',
    'Veneto',
    'Italia',
    '35121',
    'padova@universita.cam',
    '+390498001002',
    'https://padova.unisancamillo.it',
    45.4064,
    11.8768,
    'Centro universitario com foco em saude e humanizacao.'
  ),
  (
    'Hospital San Camillo Roma Centro',
    'Hospital',
    'Ativo',
    'Via delle Fornaci 27',
    'Roma',
    'Província Romana',
    'Lazio',
    'Italia',
    '00165',
    'roma.centro@camilliani.org',
    '+390668001003',
    'https://roma-centro.camilliani.org',
    41.9009,
    12.4581,
    'Hospital vinculado a servicos clinicos e assistenciais.'
  ),
  (
    'Seminario San Camillo Frascati',
    'Seminário',
    'Ativo',
    'Via Tuscolana 91',
    'Frascati',
    'Província Romana',
    'Lazio',
    'Italia',
    '00044',
    'frascati@seminario.cam',
    '+390694001004',
    'https://seminariofrascati.cam',
    41.8089,
    12.6792,
    'Seminario para formacao inicial e permanente.'
  ),
  (
    'Missao San Camillo Napoli',
    'Missão',
    'Ativo',
    'Via Duomo 144',
    'Napoli',
    'Província Siciliana-Napolitana',
    'Campania',
    'Italia',
    '80138',
    'napoli@missione.cam',
    '+390818001005',
    'https://napoli.missionecam.it',
    40.8519,
    14.2583,
    'Missao urbana com servicos de proximidade e acolhimento.'
  ),
  (
    'Casa San Camillo Palermo',
    'Outro',
    'Ativo',
    'Via Maqueda 210',
    'Palermo',
    'Província Siciliana-Napolitana',
    'Sicilia',
    'Italia',
    '90133',
    'palermo@casacam.it',
    '+390918001006',
    'https://palermo.casacam.it',
    38.1157,
    13.3615,
    'Casa religiosa de apoio a projetos pastorais e comunitarios.'
  ),
  (
    'Hospital San Camilo Madrid',
    'Hospital',
    'Ativo',
    'Calle de Alcala 210',
    'Madrid',
    'Província Espanhola',
    'Madrid',
    'Espanha',
    '28028',
    'madrid@san-camilo.es',
    '+34918001007',
    'https://madrid.sancamilo.es',
    40.4306,
    -3.6726,
    'Hospital com servicos de urgencia e internacao.'
  ),
  (
    'Centro San Camilo Sevilla',
    'Centro Universitário',
    'Ativo',
    'Avenida de la Buhaira 15',
    'Sevilla',
    'Província Espanhola',
    'Andalucia',
    'Espanha',
    '41018',
    'sevilla@centrocam.es',
    '+34954001008',
    'https://sevilla.centrocam.es',
    37.3826,
    -5.9704,
    'Centro de formacao para saude, cuidado e bioetica.'
  ),
  (
    'Krankenhaus Sankt Kamillus Berlin',
    'Hospital',
    'Ativo',
    'Mullerstrasse 45',
    'Berlin',
    'Província Alemã',
    'Berlin',
    'Alemanha',
    '13353',
    'berlin@kamillus.de',
    '+49308001009',
    'https://berlin.kamillus.de',
    52.5423,
    13.3592,
    'Hospital com atendimento clinico e assistencia espiritual.'
  ),
  (
    'Pflegeheim Sankt Kamillus Munchen',
    'Casa de Repouso',
    'Ativo',
    'Landsberger Strasse 88',
    'Munchen',
    'Província Alemã',
    'Bayern',
    'Alemanha',
    '80339',
    'munchen@pflegekamillus.de',
    '+49898001010',
    'https://munchen.pflegekamillus.de',
    48.1377,
    11.5403,
    'Casa de repouso com cuidado continuado e reabilitacao.'
  ),
  (
    'Szpital Swietego Kamila Warszawa',
    'Hospital',
    'Ativo',
    'Ulica Marszalkowska 99',
    'Warszawa',
    'Província Polonesa',
    'Mazowieckie',
    'Polonia',
    '00-693',
    'warszawa@kamilianie.pl',
    '+48228001011',
    'https://warszawa.kamilianie.pl',
    52.2298,
    21.0122,
    'Hospital dedicado ao cuidado integral e acompanhamento clinico.'
  ),
  (
    'Seminarium Swietego Kamila Krakow',
    'Seminário',
    'Ativo',
    'Ulica Grodzka 54',
    'Krakow',
    'Província Polonesa',
    'Malopolskie',
    'Polonia',
    '31-044',
    'krakow@seminariumkam.pl',
    '+48128001012',
    'https://krakow.seminariumkam.pl',
    50.0584,
    19.9383,
    'Seminario provincial para formacao religiosa e pastoral.'
  ),
  (
    'Saint Camillus Hospital Manila',
    'Hospital',
    'Ativo',
    'Taft Avenue 1140',
    'Manila',
    'Província das Filipinas',
    'Metro Manila',
    'Filipinas',
    '1004',
    'manila@camillus.ph',
    '+63288001013',
    'https://manila.camillus.ph',
    14.5648,
    120.9936,
    'Hospital de media complexidade com servicos comunitarios.'
  ),
  (
    'Camillus Mission Cebu',
    'Missão',
    'Ativo',
    'Osmena Boulevard 77',
    'Cebu City',
    'Província das Filipinas',
    'Cebu',
    'Filipinas',
    '6000',
    'cebu@missioncam.ph',
    '+63328001014',
    'https://cebu.missioncam.ph',
    10.3156,
    123.8854,
    'Missao voltada ao atendimento social e pastoral nas periferias.'
  ),
  (
    'St Camillus Hospital Bengaluru',
    'Hospital',
    'Ativo',
    'St Marks Road 52',
    'Bengaluru',
    'Província da India',
    'Karnataka',
    'India',
    '560001',
    'bengaluru@camillus.in',
    '+91808001015',
    'https://bengaluru.camillus.in',
    12.9717,
    77.5946,
    'Hospital com enfoque em saude comunitaria e reabilitacao.'
  ),
  (
    'Camillus Formation House Hyderabad',
    'Seminário',
    'Ativo',
    'Abids Road 31',
    'Hyderabad',
    'Província da India',
    'Telangana',
    'India',
    '500001',
    'hyderabad@formationcam.in',
    '+91408001016',
    'https://hyderabad.formationcam.in',
    17.385,
    78.4867,
    'Casa de formacao e estudo para religiosos e liderancas.'
  ),
  (
    'Saint Camillus Hospital Bangkok',
    'Hospital',
    'Ativo',
    'Rama IV Road 288',
    'Bangkok',
    'Província da Tailandia',
    'Bangkok',
    'Tailandia',
    '10120',
    'bangkok@camillus.or.th',
    '+6628001017',
    'https://bangkok.camillus.or.th',
    13.7244,
    100.5304,
    'Hospital com servicos clinicos e acoes de promocao da saude.'
  ),
  (
    'Camillus Mission Chiang Mai',
    'Missão',
    'Ativo',
    'Thapae Road 19',
    'Chiang Mai',
    'Província da Tailandia',
    'Chiang Mai',
    'Tailandia',
    '50100',
    'chiangmai@missioncam.or.th',
    '+66538001018',
    'https://chiangmai.missioncam.or.th',
    18.7883,
    98.9853,
    'Missao de apoio social e cuidado a comunidades vulneraveis.'
  ),
  (
    'Centre Saint Camille Cotonou',
    'Centro Universitário',
    'Ativo',
    'Boulevard Saint Michel 18',
    'Cotonou',
    'Província de Benin-Togo',
    'Littoral',
    'Benin',
    'BP 112',
    'cotonou@saintcamille.bj',
    '+22921001019',
    'https://cotonou.saintcamille.bj',
    6.3703,
    2.3912,
    'Centro de formacao e apoio em saude comunitaria.'
  ),
  (
    'Mission Saint Camille Lome',
    'Missão',
    'Ativo',
    'Avenue de la Liberation 43',
    'Lome',
    'Província de Benin-Togo',
    'Maritime',
    'Togo',
    'BP 204',
    'lome@missioncam.tg',
    '+22822001020',
    'https://lome.missioncam.tg',
    6.1319,
    1.2228,
    'Missao com foco em assistencia pastoral e servicos de base.'
  ),
  (
    'Hopital Saint Camille Ouagadougou',
    'Hospital',
    'Ativo',
    'Avenue Kwame Nkrumah 61',
    'Ouagadougou',
    'Província de Burkina Faso',
    'Centre',
    'Burkina Faso',
    '01 BP 55',
    'ouaga@saintcamille.bf',
    '+22625001021',
    'https://ouaga.saintcamille.bf',
    12.3714,
    -1.5197,
    'Hospital com atendimento geral e especialidades de apoio.'
  ),
  (
    'Paroisse Saint Camille Bobo-Dioulasso',
    'Paróquia',
    'Ativo',
    'Rue de la Cathedrale 12',
    'Bobo-Dioulasso',
    'Província de Burkina Faso',
    'Hauts-Bassins',
    'Burkina Faso',
    '01 BP 77',
    'bobo@paroissecam.bf',
    '+22627001022',
    'https://bobo.paroissecam.bf',
    11.1784,
    -4.2979,
    'Paroquia com trabalho pastoral e iniciativas comunitarias.'
  );
