INSERT INTO public.units (
  name,
  type,
  status,
  address,
  city,
  province,
  state,
  country,
  zip_code,
  email,
  phone,
  website,
  latitude,
  longitude,
  description
)
VALUES
  (
    'Hospital Sao Camilo Hanoi',
    'Hospital',
    'Ativo',
    '12 Pho Trang Thi, Hoan Kiem',
    'Hanoi',
    'Província do Vietnã',
    'Ha Noi',
    'Vietnam',
    '100000',
    'hanoi@saocamilo.vn',
    '+842438001001',
    'https://hanoi.saocamilo.vn',
    21.0285,
    105.8542,
    'Hospital com atendimento clinico e servicos de apoio a comunidade.'
  ),
  (
    'Centro Universitario Sao Camilo Ho Chi Minh',
    'Centro Universitário',
    'Ativo',
    '85 Nguyen Du, District 1',
    'Ho Chi Minh City',
    'Província do Vietnã',
    'Ho Chi Minh',
    'Vietnam',
    '700000',
    'hochiminh@universitario.saocamilo.vn',
    '+842838001002',
    'https://hochiminh.universitario.saocamilo.vn',
    10.7769,
    106.7009,
    'Centro universitario com foco em saude, bioetica e formacao profissional.'
  ),
  (
    'Paroquia Sao Camilo Da Nang',
    'Paróquia',
    'Ativo',
    '44 Bach Dang, Hai Chau',
    'Da Nang',
    'Província do Vietnã',
    'Da Nang',
    'Vietnam',
    '550000',
    'danang@paroquia.saocamilo.vn',
    '+842363001003',
    'https://danang.paroquia.saocamilo.vn',
    16.0544,
    108.2022,
    'Paroquia com atividades pastorais e atendimento social local.'
  ),
  (
    'Casa de Repouso Sao Camilo Hue',
    'Casa de Repouso',
    'Ativo',
    '18 Le Loi, Phu Hoi',
    'Hue',
    'Província do Vietnã',
    'Thua Thien Hue',
    'Vietnam',
    '530000',
    'hue@repouso.saocamilo.vn',
    '+842343001004',
    'https://hue.repouso.saocamilo.vn',
    16.4637,
    107.5909,
    'Casa de repouso voltada ao cuidado continuado de idosos.'
  ),
  (
    'Seminario Sao Camilo Nha Trang',
    'Seminário',
    'Ativo',
    '27 Tran Phu, Loc Tho',
    'Nha Trang',
    'Província do Vietnã',
    'Khanh Hoa',
    'Vietnam',
    '650000',
    'nhatrang@seminario.saocamilo.vn',
    '+842583001005',
    'https://nhatrang.seminario.saocamilo.vn',
    12.2388,
    109.1967,
    'Seminario dedicado a formacao inicial e acompanhamento vocacional.'
  ),
  (
    'Missao Sao Camilo Can Tho',
    'Missão',
    'Ativo',
    '63 Hai Ba Trung, Ninh Kieu',
    'Can Tho',
    'Província do Vietnã',
    'Can Tho',
    'Vietnam',
    '900000',
    'cantho@missao.saocamilo.vn',
    '+842923001006',
    'https://cantho.missao.saocamilo.vn',
    10.0452,
    105.7469,
    'Missao de proximidade com apoio social e pastoral comunitaria.'
  ),
  (
    'Casa Sao Camilo Hai Phong',
    'Outro',
    'Ativo',
    '101 Dien Bien Phu, Hong Bang',
    'Hai Phong',
    'Província do Vietnã',
    'Hai Phong',
    'Vietnam',
    '180000',
    'haiphong@saocamilo.vn',
    '+842253001007',
    'https://haiphong.saocamilo.vn',
    20.8449,
    106.6881,
    'Casa de apoio para acolhimento, formacao e servicos comunitarios.'
  );
